// Generated by tools/gen_intrin.py from <wmmintrin.h> (MSVC toolset) -- do not edit.
// AES-NI and PCLMULQDQ.
// 7 intrinsics. Declared at global scope with C linkage exactly as the real header
// does, under its include guard (which this file also defines, so the two can be mixed in
// either order); kstl::aes then re-exports every name, so kstl::aes::name(...) or
// `using namespace kstl::aes;` works with no SDK header included.
#include "types.hpp"
#include "sse4_2.hpp"

#ifndef KSTL_INTRIN_AES_HPP
#define KSTL_INTRIN_AES_HPP

#ifndef _INCLUDED_WMM
extern "C" {
__m128i _mm_aesdec_si128(__m128i , __m128i );
__m128i _mm_aesdeclast_si128(__m128i , __m128i );
__m128i _mm_aesenc_si128(__m128i , __m128i );
__m128i _mm_aesenclast_si128(__m128i , __m128i );
__m128i _mm_aesimc_si128(__m128i );
__m128i _mm_aeskeygenassist_si128(__m128i , const int );
__m128i _mm_clmulepi64_si128(__m128i , __m128i , const int );
}
#define _INCLUDED_WMM
#endif  // _INCLUDED_WMM

namespace kstl { namespace aes {
using ::_mm_aesdec_si128;
using ::_mm_aesdeclast_si128;
using ::_mm_aesenc_si128;
using ::_mm_aesenclast_si128;
using ::_mm_aesimc_si128;
using ::_mm_aeskeygenassist_si128;
using ::_mm_clmulepi64_si128;
} }

#endif  // KSTL_INTRIN_AES_HPP
