// Generated by tools/gen_intrin.py from <pmmintrin.h> (MSVC toolset) -- do not edit.
// SSE3.
// 13 intrinsics. Declared at global scope with C linkage exactly as the real header
// does, under its include guard (which this file also defines, so the two can be mixed in
// either order); kstl::sse3 then re-exports every name, so kstl::sse3::name(...) or
// `using namespace kstl::sse3;` works with no SDK header included.
#include "types.hpp"
#include "sse2.hpp"

#ifndef KSTL_INTRIN_SSE3_HPP
#define KSTL_INTRIN_SSE3_HPP

#ifndef _INCLUDED_PMM
extern "C" {
__m128 _mm_addsub_ps(__m128 , __m128 );
__m128 _mm_hadd_ps(__m128 , __m128 );
__m128 _mm_hsub_ps(__m128 , __m128 );
__m128 _mm_movehdup_ps(__m128 );
__m128 _mm_moveldup_ps(__m128 );
__m128d _mm_addsub_pd(__m128d , __m128d );
__m128d _mm_hadd_pd(__m128d , __m128d );
__m128d _mm_hsub_pd(__m128d , __m128d );
__m128d _mm_loaddup_pd(double const * );
__m128d _mm_movedup_pd(__m128d );
__m128i _mm_lddqu_si128(__m128i const * );
void _mm_monitor(void const * , unsigned , unsigned );
void _mm_mwait(unsigned , unsigned );
}
#define _MM_DENORMALS_ZERO_MASK   0x0040
#define _MM_DENORMALS_ZERO_ON     0x0040
#define _MM_DENORMALS_ZERO_OFF    0x0000
#define _MM_SET_DENORMALS_ZERO_MODE(mode)                                                _mm_setcsr((_mm_getcsr() & ~_MM_DENORMALS_ZERO_MASK) | (mode))
#define _MM_GET_DENORMALS_ZERO_MODE()                                                    (_mm_getcsr() & _MM_DENORMALS_ZERO_MASK)
#define _INCLUDED_PMM
#endif  // _INCLUDED_PMM

namespace kstl { namespace sse3 {
using ::_mm_addsub_ps;
using ::_mm_hadd_ps;
using ::_mm_hsub_ps;
using ::_mm_movehdup_ps;
using ::_mm_moveldup_ps;
using ::_mm_addsub_pd;
using ::_mm_hadd_pd;
using ::_mm_hsub_pd;
using ::_mm_loaddup_pd;
using ::_mm_movedup_pd;
using ::_mm_lddqu_si128;
using ::_mm_monitor;
using ::_mm_mwait;
} }

#endif  // KSTL_INTRIN_SSE3_HPP
