// Generated by tools/gen_intrin.py from <nmmintrin.h> (MSVC toolset) -- do not edit.
// SSE4.2.
// 21 intrinsics. Declared at global scope with C linkage exactly as the real header
// does, under its include guard (which this file also defines, so the two can be mixed in
// either order); kstl::sse4_2 then re-exports every name, so kstl::sse4_2::name(...) or
// `using namespace kstl::sse4_2;` works with no SDK header included.
#include "types.hpp"
#include "sse4_1.hpp"

#ifndef KSTL_INTRIN_SSE4_2_HPP
#define KSTL_INTRIN_SSE4_2_HPP

#ifndef _INCLUDED_NMM
extern "C" {
__m128i _mm_cmpistrm (__m128i , __m128i , const int );
int _mm_cmpistri (__m128i , __m128i , const int );
__m128i _mm_cmpestrm (__m128i , int , __m128i , int , const int );
int _mm_cmpestri (__m128i , int , __m128i , int , const int );
int _mm_cmpistrz (__m128i , __m128i , const int );
int _mm_cmpistrc (__m128i , __m128i , const int );
int _mm_cmpistrs (__m128i , __m128i , const int );
int _mm_cmpistro (__m128i , __m128i , const int );
int _mm_cmpistra (__m128i , __m128i , const int );
int _mm_cmpestrz (__m128i , int , __m128i , int , const int );
int _mm_cmpestrc (__m128i , int , __m128i , int , const int );
int _mm_cmpestrs (__m128i , int , __m128i , int , const int );
int _mm_cmpestro (__m128i , int , __m128i , int , const int );
int _mm_cmpestra (__m128i , int , __m128i , int , const int );
__m128i _mm_cmpgt_epi64(__m128i , __m128i );
int _mm_popcnt_u32(unsigned int );
__int64 _mm_popcnt_u64(unsigned __int64 );
unsigned int _mm_crc32_u8 (unsigned int , unsigned char );
unsigned int _mm_crc32_u16(unsigned int , unsigned short );
unsigned int _mm_crc32_u32(unsigned int , unsigned int );
unsigned __int64 _mm_crc32_u64(unsigned __int64 , unsigned __int64 );
}
#define _SIDD_UBYTE_OPS                0x00
#define _SIDD_UWORD_OPS                0x01
#define _SIDD_SBYTE_OPS                0x02
#define _SIDD_SWORD_OPS                0x03
#define _SIDD_CMP_EQUAL_ANY            0x00
#define _SIDD_CMP_RANGES               0x04
#define _SIDD_CMP_EQUAL_EACH           0x08
#define _SIDD_CMP_EQUAL_ORDERED        0x0C
#define _SIDD_POSITIVE_POLARITY        0x00
#define _SIDD_NEGATIVE_POLARITY        0x10
#define _SIDD_MASKED_POSITIVE_POLARITY 0x20
#define _SIDD_MASKED_NEGATIVE_POLARITY 0x30
#define _SIDD_LEAST_SIGNIFICANT        0x00
#define _SIDD_MOST_SIGNIFICANT         0x40
#define _SIDD_BIT_MASK                 0x00
#define _SIDD_UNIT_MASK                0x40
#define _INCLUDED_NMM
#endif  // _INCLUDED_NMM

namespace kstl { namespace sse4_2 {
using ::_mm_cmpistrm;
using ::_mm_cmpistri;
using ::_mm_cmpestrm;
using ::_mm_cmpestri;
using ::_mm_cmpistrz;
using ::_mm_cmpistrc;
using ::_mm_cmpistrs;
using ::_mm_cmpistro;
using ::_mm_cmpistra;
using ::_mm_cmpestrz;
using ::_mm_cmpestrc;
using ::_mm_cmpestrs;
using ::_mm_cmpestro;
using ::_mm_cmpestra;
using ::_mm_cmpgt_epi64;
using ::_mm_popcnt_u32;
using ::_mm_popcnt_u64;
using ::_mm_crc32_u8;
using ::_mm_crc32_u16;
using ::_mm_crc32_u32;
using ::_mm_crc32_u64;
} }

#endif  // KSTL_INTRIN_SSE4_2_HPP
