// Generated by tools/gen_intrin.py from <smmintrin.h> (MSVC toolset) -- do not edit.
// SSE4.1.
// 50 intrinsics. Declared at global scope with C linkage exactly as the real header
// does, under its include guard (which this file also defines, so the two can be mixed in
// either order); kstl::sse4_1 then re-exports every name, so kstl::sse4_1::name(...) or
// `using namespace kstl::sse4_1;` works with no SDK header included.
#include "types.hpp"
#include "ssse3.hpp"

#ifndef KSTL_INTRIN_SSE4_1_HPP
#define KSTL_INTRIN_SSE4_1_HPP

#ifndef _INCLUDED_SMM
extern "C" {
__m128i _mm_blend_epi16 (__m128i, __m128i, const int );
__m128i _mm_blendv_epi8 (__m128i, __m128i, __m128i mask);
__m128 _mm_blend_ps (__m128, __m128, const int );
__m128 _mm_blendv_ps(__m128, __m128, __m128 );
__m128d _mm_blend_pd (__m128d, __m128d, const int );
__m128d _mm_blendv_pd(__m128d, __m128d, __m128d );
__m128 _mm_dp_ps(__m128, __m128, const int );
__m128d _mm_dp_pd(__m128d, __m128d, const int );
__m128i _mm_cmpeq_epi64(__m128i, __m128i);
__m128i _mm_min_epi8 (__m128i, __m128i);
__m128i _mm_max_epi8 (__m128i, __m128i);
__m128i _mm_min_epu16(__m128i, __m128i);
__m128i _mm_max_epu16(__m128i, __m128i);
__m128i _mm_min_epi32(__m128i, __m128i);
__m128i _mm_max_epi32(__m128i, __m128i);
__m128i _mm_min_epu32(__m128i, __m128i);
__m128i _mm_max_epu32(__m128i, __m128i);
__m128i _mm_mullo_epi32(__m128i, __m128i);
__m128i _mm_mul_epi32(__m128i, __m128i);
int _mm_testz_si128(__m128i , __m128i );
int _mm_testc_si128(__m128i , __m128i );
int _mm_testnzc_si128(__m128i , __m128i );
__m128 _mm_insert_ps(__m128 , __m128 , const int );
int _mm_extract_ps(__m128 , const int );
__m128i _mm_insert_epi8 (__m128i , int , const int );
__m128i _mm_insert_epi32(__m128i , int , const int );
__m128i _mm_insert_epi64(__m128i , __int64 , const int );
int _mm_extract_epi8 (__m128i , const int );
int _mm_extract_epi32(__m128i , const int );
__int64 _mm_extract_epi64(__m128i , const int );
__m128i _mm_minpos_epu16(__m128i);
__m128d _mm_round_pd(__m128d , int );
__m128d _mm_round_sd(__m128d , __m128d , int );
__m128 _mm_round_ps(__m128 , int );
__m128 _mm_round_ss(__m128 , __m128 , int );
__m128i _mm_cvtepi8_epi32 (__m128i);
__m128i _mm_cvtepi16_epi32(__m128i);
__m128i _mm_cvtepi8_epi64 (__m128i);
__m128i _mm_cvtepi32_epi64(__m128i);
__m128i _mm_cvtepi16_epi64(__m128i);
__m128i _mm_cvtepi8_epi16 (__m128i);
__m128i _mm_cvtepu8_epi32 (__m128i);
__m128i _mm_cvtepu16_epi32(__m128i);
__m128i _mm_cvtepu8_epi64 (__m128i);
__m128i _mm_cvtepu32_epi64(__m128i);
__m128i _mm_cvtepu16_epi64(__m128i);
__m128i _mm_cvtepu8_epi16 (__m128i);
__m128i _mm_packus_epi32(__m128i, __m128i);
__m128i _mm_mpsadbw_epu8(__m128i , __m128i , const int );
__m128i _mm_stream_load_si128(const __m128i*);
}
#define _MM_FROUND_TO_NEAREST_INT    0x00
#define _MM_FROUND_TO_NEG_INF        0x01
#define _MM_FROUND_TO_POS_INF        0x02
#define _MM_FROUND_TO_ZERO           0x03
#define _MM_FROUND_CUR_DIRECTION     0x04
#define _MM_FROUND_RAISE_EXC         0x00
#define _MM_FROUND_NO_EXC            0x08
#define _MM_FROUND_NINT      _MM_FROUND_TO_NEAREST_INT | _MM_FROUND_RAISE_EXC
#define _MM_FROUND_FLOOR     _MM_FROUND_TO_NEG_INF     | _MM_FROUND_RAISE_EXC
#define _MM_FROUND_CEIL      _MM_FROUND_TO_POS_INF     | _MM_FROUND_RAISE_EXC
#define _MM_FROUND_TRUNC     _MM_FROUND_TO_ZERO        | _MM_FROUND_RAISE_EXC
#define _MM_FROUND_RINT      _MM_FROUND_CUR_DIRECTION  | _MM_FROUND_RAISE_EXC
#define _MM_FROUND_NEARBYINT _MM_FROUND_CUR_DIRECTION  | _MM_FROUND_NO_EXC
#define _mm_ceil_pd(val)       _mm_round_pd((val), _MM_FROUND_CEIL)
#define _mm_ceil_sd(dst, val)  _mm_round_sd((dst), (val), _MM_FROUND_CEIL)
#define _mm_floor_pd(val)      _mm_round_pd((val), _MM_FROUND_FLOOR)
#define _mm_floor_sd(dst, val) _mm_round_sd((dst), (val), _MM_FROUND_FLOOR)
#define _mm_ceil_ps(val)       _mm_round_ps((val), _MM_FROUND_CEIL)
#define _mm_ceil_ss(dst, val)  _mm_round_ss((dst), (val), _MM_FROUND_CEIL)
#define _mm_floor_ps(val)      _mm_round_ps((val), _MM_FROUND_FLOOR)
#define _mm_floor_ss(dst, val) _mm_round_ss((dst), (val), _MM_FROUND_FLOOR)
#define _mm_test_all_zeros(mask, val)      _mm_testz_si128((mask), (val))
#define _mm_test_all_ones(val)                _mm_testc_si128((val), _mm_cmpeq_epi32((val),(val)))
#define _mm_test_mix_ones_zeros(mask, val) _mm_testnzc_si128((mask), (val))
#define _MM_MK_INSERTPS_NDX(srcField, dstField, zeroMask)          (((srcField)<<6) | ((dstField)<<4) | (zeroMask))
#define _MM_EXTRACT_FLOAT(dest, src, ndx)          *((int*)&(dest)) = _mm_extract_ps((src), (ndx))
#define _MM_PICK_OUT_PS(src, num)          _mm_insert_ps(_mm_setzero_ps(), (src),                        _MM_MK_INSERTPS_NDX((num), 0, 0x0e))
#define _INCLUDED_SMM
#endif  // _INCLUDED_SMM

namespace kstl { namespace sse4_1 {
using ::_mm_blend_epi16;
using ::_mm_blendv_epi8;
using ::_mm_blend_ps;
using ::_mm_blendv_ps;
using ::_mm_blend_pd;
using ::_mm_blendv_pd;
using ::_mm_dp_ps;
using ::_mm_dp_pd;
using ::_mm_cmpeq_epi64;
using ::_mm_min_epi8;
using ::_mm_max_epi8;
using ::_mm_min_epu16;
using ::_mm_max_epu16;
using ::_mm_min_epi32;
using ::_mm_max_epi32;
using ::_mm_min_epu32;
using ::_mm_max_epu32;
using ::_mm_mullo_epi32;
using ::_mm_mul_epi32;
using ::_mm_testz_si128;
using ::_mm_testc_si128;
using ::_mm_testnzc_si128;
using ::_mm_insert_ps;
using ::_mm_extract_ps;
using ::_mm_insert_epi8;
using ::_mm_insert_epi32;
using ::_mm_insert_epi64;
using ::_mm_extract_epi8;
using ::_mm_extract_epi32;
using ::_mm_extract_epi64;
using ::_mm_minpos_epu16;
using ::_mm_round_pd;
using ::_mm_round_sd;
using ::_mm_round_ps;
using ::_mm_round_ss;
using ::_mm_cvtepi8_epi32;
using ::_mm_cvtepi16_epi32;
using ::_mm_cvtepi8_epi64;
using ::_mm_cvtepi32_epi64;
using ::_mm_cvtepi16_epi64;
using ::_mm_cvtepi8_epi16;
using ::_mm_cvtepu8_epi32;
using ::_mm_cvtepu16_epi32;
using ::_mm_cvtepu8_epi64;
using ::_mm_cvtepu32_epi64;
using ::_mm_cvtepu16_epi64;
using ::_mm_cvtepu8_epi16;
using ::_mm_packus_epi32;
using ::_mm_mpsadbw_epu8;
using ::_mm_stream_load_si128;
} }

#endif  // KSTL_INTRIN_SSE4_1_HPP
