// Generated by tools/gen_intrin.py from <tmmintrin.h> (MSVC toolset) -- do not edit.
// SSSE3.
// 16 intrinsics. Declared at global scope with C linkage exactly as the real header
// does, under its include guard (which this file also defines, so the two can be mixed in
// either order); kstl::ssse3 then re-exports every name, so kstl::ssse3::name(...) or
// `using namespace kstl::ssse3;` works with no SDK header included.
#include "types.hpp"
#include "sse3.hpp"

#ifndef KSTL_INTRIN_SSSE3_HPP
#define KSTL_INTRIN_SSSE3_HPP

#ifndef _INCLUDED_TMM
extern "C" {
__m128i _mm_hadd_epi16 (__m128i, __m128i);
__m128i _mm_hadd_epi32 (__m128i, __m128i);
__m128i _mm_hadds_epi16 (__m128i, __m128i);
__m128i _mm_hsub_epi16 (__m128i, __m128i);
__m128i _mm_hsub_epi32 (__m128i, __m128i);
__m128i _mm_hsubs_epi16 (__m128i, __m128i);
__m128i _mm_maddubs_epi16 (__m128i, __m128i);
__m128i _mm_mulhrs_epi16 (__m128i, __m128i);
__m128i _mm_shuffle_epi8 (__m128i, __m128i);
__m128i _mm_sign_epi8 (__m128i, __m128i);
__m128i _mm_sign_epi16 (__m128i, __m128i);
__m128i _mm_sign_epi32 (__m128i, __m128i);
__m128i _mm_alignr_epi8 (__m128i, __m128i, int);
__m128i _mm_abs_epi8 (__m128i);
__m128i _mm_abs_epi16 (__m128i);
__m128i _mm_abs_epi32 (__m128i);
}
#define _MM_FUNCTIONALITY
#define _INCLUDED_TMM
#endif  // _INCLUDED_TMM

namespace kstl { namespace ssse3 {
using ::_mm_hadd_epi16;
using ::_mm_hadd_epi32;
using ::_mm_hadds_epi16;
using ::_mm_hsub_epi16;
using ::_mm_hsub_epi32;
using ::_mm_hsubs_epi16;
using ::_mm_maddubs_epi16;
using ::_mm_mulhrs_epi16;
using ::_mm_shuffle_epi8;
using ::_mm_sign_epi8;
using ::_mm_sign_epi16;
using ::_mm_sign_epi32;
using ::_mm_alignr_epi8;
using ::_mm_abs_epi8;
using ::_mm_abs_epi16;
using ::_mm_abs_epi32;
} }

#endif  // KSTL_INTRIN_SSSE3_HPP
