// Generated by tools/gen_intrin.py -- do not edit.
// size_t is not a builtin. The toolset declares it as exactly this, and an identical typedef may
// be repeated, so this is safe whether or not a CRT header came first. The vector, mask and enum
// types live in the family header that stands in for the toolset header defining them.
#pragma once

typedef unsigned __int64 size_t;
