// kstl/intrin.hpp -- every x64 intrinsic the MSVC toolset knows, declared ourselves so nothing
// needs <intrin.h>, <emmintrin.h>, <immintrin.h> or friends. One file per instruction-set family
// under intrin/, each with a kstl::<family> namespace; this umbrella includes them all. Include
// only the family you need in hot headers (hash_map.hpp takes x64 and sse2) -- this file is for
// convenience and for the test that exercises everything.
//
// Generated by tools/gen_intrin.py; regenerate after a toolset update. Every declaration is the
// toolset's own, byte for byte, which is what makes MSVC treat the name as an intrinsic.
#pragma once
#include "intrin/x64.hpp"
#include "intrin/sse.hpp"
#include "intrin/sse2.hpp"
#include "intrin/sse3.hpp"
#include "intrin/ssse3.hpp"
#include "intrin/sse4_1.hpp"
#include "intrin/sse4_2.hpp"
#include "intrin/sse4a.hpp"
#include "intrin/aes.hpp"
#include "intrin/avx.hpp"
#include "intrin/avx512.hpp"
